import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

import Menu from '@/components/menu'

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Menu />

				<div className="md:pl-64 flex flex-col flex-1 bg-gray-100 min-h-screen">
					{children}
				</div>
			</body>
		</html>
	)
}
